### ISSUE TITLE
Info not shown nor updated

### ISSUE THREAD

**Issue by EmAnzi3** [caiosweet/Home-Assistant-custom-components-DPC-Alert#24]
Hello,
I apparently managed to configure the DPC Alert adding to `configuration.yaml` the following lines:
```
binary_sensor:
  - platform: dpc
    name: DPC Massarosa
    istat: '046018'
    alert: 'gialla'
    warnings:
      - temporali_oggi
      - idraulico_oggi
      - idrogeologico_oggi
      - temporali_domani
      - idraulico_domani
      - idrogeologico_domani
```
However, I'm unable to visualize the info using the proposed examples like "Example Lovelace markdown card" or "Example Lovelace card auto-entities and card-mod"; plugins regularly installed via HACS, for example with below configuration I get only an empty card:
```
type: 'custom:auto-entities'
card:
  type: entities
  show_empty: false
  style: |
    ha-card {background: none; border-radius: 0px; box-shadow: none;}
filter:
  include:
    - entity_id: binary_sensor.dpc_massarosa_idraulico_oggi
      state: 'on'
      options:
        entity: this.entity_id
        secondary_info: last-changed
        style: |
          :host {
            --color:
              {% set color = {0:'White', 1:'Green', 2:'Yellow', 3:'Orange', 4:'Red'} %}
              {{color[state_attr(config.entity, 'level')|int]}}
            color: var(--color);
            --paper-item-icon-color: var(--color);
          }
```
The only way to visualize them is to use the Entities card but I get "safe" for all the 6 entities even if I know that those shouldn't be on that status. Am I doing something wrong?
