### ISSUE TITLE
Missing sensors

### ISSUE THREAD

**Issue by enribomber** [caiosweet/Home-Assistant-custom-components-DPC-Alert#26]
Hi, I installed the component with HACS and copied the config from the example, but the sensors are not being created.

**Comment by caiosweet** [comment]
Can you please share your configuration? 
What is your operating system?
What kind of HomeAssistant installation do you have?
Are there any errors in the log?

**Comment by caiosweet** [comment]
Can you please share your configuration?
What is your operating system?
What kind of HomeAssistant installation do you have?
Are there any errors in the log?

**Comment by enribomber** [comment]
Hi, i'm running Hassio on docker on a RP3B+

Ha core 2021.2.3

Config below (tried to modify with our without name, adding or taking out "gialla" but no changes)

binary_sensor:
  - platform: workday
    country: IT
    
  - platform: dpc
#    name: Ferrara
    istat: '038008'
    warnings:
      - temporali_oggi
      - idraulico_oggi
      - idrogeologico_oggi
      - temporali_domani
      - idraulico_domani
      - idrogeologico_domani


> 
> 
> Can you please share your configuration?
> What is your operating system?
> What kind of HomeAssistant installation do you have?
> Are there any errors in the log?

**Comment by caiosweet** [comment]
The configuration is right.

I'm a little confused ... you name hassio (old name) so it would be supervised with HassOS?

If you use "hassio" you will surely have the supervisor, so there should be no problems with dependencies and resources. (see the feedparser module)

(Are there any errors or warnings in the log?)

If, on the other hand, in the log you have a similar writing

**No module named 'feedparser'**

then the module must be installed manually
`pip install feedparser`


configuratrion.yaml

```
binary_sensor:
  - platform: dpc
    #name: DPC Ferrara
    istat: '046018'
    #alert: 'gialla'
    warnings:
      - temporali_oggi
      - idraulico_oggi
      - idrogeologico_oggi
      - temporali_domani
      - idraulico_domani
      - idrogeologico_domani
    # scan_interval: 900
```

Lovelace card

```
type: entities
entities:
  - entity: binary_sensor.dpc_temporali_oggi
  - entity: binary_sensor.dpc_idraulico_oggi
  - entity: binary_sensor.dpc_idrogeologico_oggi
  - entity: binary_sensor.dpc_temporali_domani
  - entity: binary_sensor.dpc_idraulico_domani
  - entity: binary_sensor.dpc_idrogeologico_domani
title: Ferrara
```

**Comment by mfabiani53** [comment]
Same problem here.... after the latest update the binary_sensor is not created anymore.
I am running Hassio 2021.2.3.
My config:
```
- platform: dpc
  name: DPC Avezzano
  istat: '066006'
  alert: 'gialla'
  warnings:
    - temporali_oggi
    - idraulico_oggi
    - idrogeologico_oggi
    - temporali_domani
    - idraulico_domani
    - idrogeologico_domani 
    ```

**Comment by enribomber** [comment]
> 
> 
> The configuration is right.
> 
> I'm a little confused ... you name hassio (old name) so it would be supervised with HassOS?
> 
> If you use "hassio" you will surely have the supervisor, so there should be no problems with dependencies and resources. (see the feedparser module)
> 
> (Are there any errors or warnings in the log?)
> 
> If, on the other hand, in the log you have a similar writing
> 
> **No module named 'feedparser'**
> 
> then the module must be installed manually
> `pip install feedparser`
> 
> configuratrion.yaml
> 
> ```
> binary_sensor:
>   - platform: dpc
>     #name: DPC Ferrara
>     istat: '046018'
>     #alert: 'gialla'
>     warnings:
>       - temporali_oggi
>       - idraulico_oggi
>       - idrogeologico_oggi
>       - temporali_domani
>       - idraulico_domani
>       - idrogeologico_domani
>     # scan_interval: 900
> ```
> 
> Lovelace card
> 
> ```
> type: entities
> entities:
>   - entity: binary_sensor.dpc_temporali_oggi
>   - entity: binary_sensor.dpc_idraulico_oggi
>   - entity: binary_sensor.dpc_idrogeologico_oggi
>   - entity: binary_sensor.dpc_temporali_domani
>   - entity: binary_sensor.dpc_idraulico_domani
>   - entity: binary_sensor.dpc_idrogeologico_domani
> title: Ferrara
> ```

yes i'm running supervisor, version supervisor-2021.02.11

not sure about the feedparser module, how can i be sure this is installed?

**Comment by caiosweet** [comment]
I don't think this is the problem, but if the module doesn't exist, it comes out written in the log.

I would like to help you, but you should see the log if it shows any anomalies.

To have a more complete log you could activate debugging like this:

(in the configuration.yaml file)

```
logger:
   default: warn
   logs:
     custom_components.dpc.binary_sensor: debug

```
Try to:

1. Uninstall the DPC component from HACS.
2. Restart Home Assistant.
3. Install the DPC component again.
4. Restart Home Assistant.
5. Look in the log (From UI Configuration -> Logs -> Load full home assistant log) if there is any error related to dpc and paste it here in this thread.
