### ISSUE TITLE
Errore Automazione

### ISSUE THREAD

**Issue by Sblackk** [caiosweet/Home-Assistant-custom-components-DPC-Alert#33]
Buona sera...

ho installato già da tempo questo componente di Home Assistant e devo dire che mi trovo molto bene...
sempre preciso ed aggiornato.

L'unico problema lo riscontro con l'automazione.

L'errore che mi genera è il seguente:

2021-04-29 20:05:29 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'to_state' when rendering '{{trigger.to_state.attributes}}'
2021-04-29 20:05:29 ERROR (MainThread) [homeassistant.components.automation.0_protezione_civile_notifications_duplica] 0natural_events_protezione_civile_notification: Error executing script. Error rendering template for variables at pos 1: UndefinedError: 'dict object' has no attribute 'to_state'
2021-04-29 20:05:29 ERROR (MainThread) [homeassistant.components.automation.0_protezione_civile_notifications_duplica] Error while executing automation automation.0_protezione_civile_notifications_duplica: UndefinedError: 'dict object' has no attribute 'to_state'

Core
Versione
core-2021.4.6

Mi dai un aiuto a risolvere...?!?

**Comment by caiosweet** [comment]
Ciao...
dall'errore, si vede che hai premuto il pulsante "esegui azioni" dall'automazione.
Non è così che va usata, ci sono i trigger e se se non vengono popolati, difficilmente funzionerà.
Hai intenzione di provare se funziona? Impostato lo stato di uno dei sensori in 'on' :0)

**Comment by Sblackk** [comment]
Si, hai ragione, ma le ho provate proprio tutte... questo è l'errore che ho quando attivo un interruttore manualmente.

2021-04-30 00:05:14 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: dict object has no element 0 when rendering '{% set risk = {none: '❌', 'Temporali':'⚡', 'Idraulico':'💧', 'Idrogeologico':'🌊'} %}
{{risk[attr.get('rischio')]}} {{attr.get('friendly_name')}}.
{{alert[attr.get('level', 0)].color}} Allerta {{attr.get('allerta')}} {{attr.get('info')}}.
[Bollettino di criticità]({{trigger.to_state.attributes.link}})'
2021-04-30 00:05:14 ERROR (MainThread) [homeassistant.components.automation.0allarme_meteo_personalizzato] 0 Protezione Civile Notifications: Error executing script. Error for call_service at pos 2: Error rendering data template: UndefinedError: dict object has no element 0
2021-04-30 00:05:14 ERROR (MainThread) [homeassistant.components.automation.0allarme_meteo_personalizzato] Error while executing automation automation.0allarme_meteo_personalizzato: Error rendering data template: UndefinedError: dict object has no element 0
2021-04-30 00:05:37 ERROR (MainThread) [custom_components.localtuya.common] [805...28f] Connect to 192.168.1.61 failed

**Comment by caiosweet** [comment]
Questo errore è dovuto alla formattazione errata dei codice. Probabilmente starai usando l'editor UI.
Ti suggerisco di creare un'automazione più semplice, o utilizzare le automazioni manuali.

**Comment by caiosweet** [comment]
La ragione dell'errore in UI, è la conversione in stringa del codice. Il seguente codice dovrebbe funzionare copiando in mode yaml nell'automazioni in UI.

```
alias: DPC
trigger:
  - platform: state
    entity_id:
      - binary_sensor.dpc_idrogeologico_oggi
      - binary_sensor.dpc_idraulico_oggi
      - binary_sensor.dpc_temporali_oggi
      - binary_sensor.dpc_idrogeologico_domani
      - binary_sensor.dpc_idraulico_domani
      - binary_sensor.dpc_temporali_domani
condition:
  - condition: template
    value_template: >-
      {{ trigger.to_state.state == 'on' and (trigger.from_state.state == 'off' 
      or (trigger.to_state.attributes != trigger.from_state.attributes))}}
action:
  - variables:
      attr: '{{trigger.to_state.attributes}}'
      alert:
        '0':
          color: ⚪
          text: Bianca
        '1':
          color: "\U0001F7E2"
          text: Verde
        '2':
          color: "\U0001F7E1"
          text: Gialla
        '3':
          color: "\U0001F7E0"
          text: Arancione
        '4':
          color: "\U0001F534"
          text: Rossa
      dpc_tts_msg: >-
        Attenzione. {{attr.get('friendly_name')}}. Allerta
        {{attr.get('allerta')}} {{attr.get('info')}}.
  - service: notify.pushover
    data:
      title: >-
        Protezione Civile - {{attr.get('rischio')}}{% if
        trigger.from_state.state == 'on' %} - Revisione{% endif %}
      message: "{% set risk = {none: '❌', 'Temporali':'⚡', 'Idraulico':'\U0001F4A7', 'Idrogeologico':'\U0001F30A'} %}\n{{risk[attr.get('rischio')]}} {{attr.get('friendly_name')}}. \n{{alert[attr.get('level', '0')|string].color}} Allerta {{attr.get('allerta')}} {{attr.get('info')}}.\n\n[Bollettino di criticità]({{trigger.to_state.attributes.link}})\n"
  - service: tts.google_translate_say
    data:
      message: '{{dpc_tts_msg}}'
      entity_id: media_player.red
mode: queued
max_exceeded: silent
initial_state: true
max: 10

```
