### ISSUE TITLE
Home Assistant 5.4 DPC not working - sensor not exist

### ISSUE THREAD

**Issue by matfil92** [caiosweet/Home-Assistant-custom-components-DPC-Alert#35]
Hi,
I've installed today the DPC with HACS. The version of DPC is 2021.4.0 and Home Assistant Version is core-2021.5.4 with supervisor-2021.04.3.

After I've installed the DPC I've put this configuration in configuration.yaml

#ProtezioneCivile
binary_sensor:
  - platform: dpc
    name: DPC Vaprio
    istat: '015230'
    alert: 'gialla'
    warnings:
      - temporali_oggi

After many reboot of supervisor no sensors appear with name dpc. 
I've also tried previous version of DPC (2021.3.1) with reboot but nothing will change.

I've also tried to left only -temporali_oggi and not more entities but nothing will change, sensor will not appear.

Could you please help me?

**Comment by caiosweet** [comment]
I tested your setup on a raspberry with HassOS and all the latest updates.

```
binary_sensor:
  - platform: dpc
    name: DPC Vaprio
    istat: '015230'
    alert: 'gialla'
    warnings:
      - temporali_oggi
    #  - idraulico_oggi
    #  - idrogeologico_oggi
    #  - temporali_domani
    #  - idraulico_domani
    #  - idrogeologico_domani
    # scan_interval: 900
```

Everything works.


Can you please check the log and see if there are any errors?
You can also enable debugging like this:

```
logger:
  default: warn
  logs:
    custom_components.dpc.binary_sensor: debug
```

**Comment by matfil92** [comment]
I'm sorry, now it's working correctly.

I've check that I had 2 binary_sensor and is possible only to have one.

**Comment by caiosweet** [comment]
> I'm sorry, now it's working correctly.
> 
> I've check that I had 2 binary_sensor and is possible only to have one.

Not exactly. 
If you want multiple binary sensors for different locations, 
you need to enter the data like this:

```
binary_sensor:
  - platform: dpc
    name: DPC Vaprio
    istat: '015230'
    alert: 'gialla'
    warnings:
      - temporali_oggi
      - idraulico_oggi
      - idrogeologico_oggi
      - temporali_domani
      - idraulico_domani
      - idrogeologico_domani

  - platform: dpc
    name: DPC Roma
    istat: '058091'
    alert: 'gialla'
    warnings:
      - temporali_oggi
      - idraulico_oggi
      - idrogeologico_oggi
      - temporali_domani
      - idraulico_domani
      - idrogeologico_domani

  - platform: dpc
    name: DPC Campobasso
    istat: '070006'
    alert: 'gialla'
    warnings:
      - temporali_oggi
```

**Edit**

Ah, yes, only one "`binary_sesor:`" must be entered in the same place.
#### This cannot be done:

```
binary_sensor:
  - platform: dpc
    name: DPC Vaprio
    istat: '015230'
    alert: 'gialla'
    warnings:
      - temporali_oggi
      - idraulico_oggi
      - idrogeologico_oggi
      - temporali_domani
      - idraulico_domani
      - idrogeologico_domani

binary_sensor:
  - platform: dpc
    name: DPC Roma
    istat: '058091'
    alert: 'gialla'
    warnings:
      - temporali_oggi
```
